name: build-latest

on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    buildx:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Github
              run: echo ${{ secrets.GHCR_KEY }} | docker login https://ghcr.io -u outsideris --password-stdin
            - name: Build and Push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
                  push: true
                  tags: ghcr.io/lemon-mint/event-broker:latest
